// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('00_Navbar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('00_Navbar', async function() {
    await driver.get("http://localhost:3000/")
    vars["userID"] = await driver.executeScript("return localStorage.getItem(\"userID\")")
    if (!!await driver.executeScript("return (arguments[0] != null)", vars["userID"])) {
      console.log(vars["userID"])
      await driver.findElement(By.linkText("Logout")).click()
      vars["userID"] = await driver.executeScript("return localStorage.getItem(\"userID\")")
      await driver.get("http://localhost:3000/register")
      console.log(vars["userID"])
    }
    await driver.findElement(By.linkText("Home")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/")
    await driver.findElement(By.linkText("About")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/about")
    await driver.findElement(By.linkText("Product")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/product")
    await driver.findElement(By.linkText("Login")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/login")
    await driver.findElement(By.linkText("Register")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/register")
    await driver.findElement(By.linkText("Stav")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/stav")
    await driver.findElement(By.linkText("Adar")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/adar")
    await driver.findElement(By.linkText("Ido")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/Ido")
    await driver.findElement(By.css("path")).click()
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/cart")
  })
})
