// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('01_Register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('01_Register', async function() {
    await driver.get("http://localhost:3000/")
    vars["userID"] = await driver.executeScript("return localStorage.getItem(\"userID\")")
    if (!!await driver.executeScript("return (arguments[0] != null)", vars["userID"])) {
      console.log(vars["userID"])
      await driver.findElement(By.linkText("Logout")).click()
      vars["userID"] = await driver.executeScript("return localStorage.getItem(\"userID\")")
      await driver.get("http://localhost:3000/login")
      console.log(vars["userID"])
    }
    await driver.get("http://localhost:3000/register")
    await driver.findElement(By.id("email")).sendKeys(" test@test.test")
    await driver.findElement(By.id("password")).sendKeys("test123")
    await driver.findElement(By.id("cnfrm-password")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    const messageElement = await driver.findElement(By.id("message"));
    const messageText = await messageElement.getText();
    await driver.sleep(2000);
    console.log(messageElement.getText());
    await driver.sleep(2000);
    assert.equal(messageText,"Email already exists");
    await driver.findElement(By.id("cnfrm-password")).sendKeys("test12")
    await driver.findElement(By.css(".btn")).click()
    const messageElement1 = await driver.findElement(By.id("message"));
    const messageText1 = await messageElement1.getText();
    await driver.sleep(2000);
    console.log(messageElement1.getText());
    await driver.sleep(2000);
    assert.equal(messageText1,"Error! passwords not match");
    await driver.findElement(By.id("cnfrm-password")).sendKeys(" ")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! fields can\\\'t be empty")
    await driver.findElement(By.id("cnfrm-password")).sendKeys("test123")
    await driver.findElement(By.id("password")).sendKeys(" ")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! fields can\\\'t be empty")
    await driver.findElement(By.id("password")).sendKeys("test123")
    await driver.findElement(By.id("email")).sendKeys(" ")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! fields can\\\'t be empty")
    await driver.findElement(By.id("email")).sendKeys(" test@test")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! email is invalid")
    await driver.findElement(By.id("email")).sendKeys("test.test")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! email is invalid")
    await driver.findElement(By.id("email")).sendKeys(" @test.test")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! email is invalid")
    await driver.findElement(By.id("email")).sendKeys(" test@.test")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! email is invalid")
    await driver.findElement(By.id("email")).sendKeys(" test@test.")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.id("message")).getText() == "Error! email is invalid")
    await driver.get("http://localhost:3000/login")
    await driver.findElement(By.id("email")).sendKeys("test@test.test")
    await driver.findElement(By.id("password")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.switchTo().alert().getText() == "Login successfully!")
    await driver.findElement(By.linkText("Delete User")).click()
    assert(await driver.switchTo().alert().getText() == "User deleted successfully!")
    await driver.get("http://localhost:3000/register")
    await driver.findElement(By.id("email")).sendKeys(" test@test.test")
    await driver.findElement(By.id("password")).sendKeys("test123")
    await driver.findElement(By.id("cnfrm-password")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.switchTo().alert().getText() == "Registration successfully!")
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:3000/login")
  })
})
