// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('03_AddToCart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('03_AddToCart', async function() {
    await driver.get("http://localhost:3000/product")
    await driver.findElement(By.css(".single-product:nth-child(1) .bg-sky-400")).click()
    vars["cart"] = await driver.findElement(By.css("a > span")).getText()
    assert(vars["cart"].toString() == "1")
    await driver.findElement(By.css(".single-product:nth-child(1) .bg-sky-400")).click()
    vars["cart"] = await driver.findElement(By.css("a > span")).getText()
    assert(vars["cart"].toString() == "2")
    await driver.findElement(By.css("#graphics\\ card > span")).click()
    await driver.findElement(By.css("#Keyboard > span")).click()
    await driver.findElement(By.css("#earbuds > span")).click()
    await driver.findElement(By.css("#smartwatch > span")).click()
    await driver.findElement(By.css("#laptop > span")).click()
    await driver.findElement(By.css("#smartphone > span")).click()
    await driver.findElement(By.css(".select-none > .font-semibold")).click()
    await driver.findElement(By.css(".single-product:nth-child(4) .bg-sky-400")).click()
    vars["cart"] = await driver.findElement(By.css("a > span")).getText()
    assert(vars["cart"].toString() == "3")
    await driver.findElement(By.css("path")).click()
    await driver.findElement(By.css(".product:nth-child(2) button:nth-child(5)")).click()
    vars["cart"] = await driver.findElement(By.css("a > span")).getText()
    assert(vars["cart"].toString() == "4")
    vars["quantity"] = await driver.findElement(By.css(".product:nth-child(1) p:nth-child(4)")).getText()
    assert(vars["quantity"].toString() == "Quantity: 2")
    await driver.findElement(By.css(".product:nth-child(1) button:nth-child(6)")).click()
    vars["quantity"] = await driver.findElement(By.css(".product:nth-child(1) p:nth-child(4)")).getText()
    assert(vars["quantity"].toString() == "Quantity: 1")
    vars["cart"] = await driver.findElement(By.css("a > span")).getText()
    assert(vars["cart"].toString() == "3")
  })
})
