// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('05_DeleteUser', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('05_DeleteUser', async function() {
    await driver.get("http://localhost:3000/")
    vars["userID"] = await driver.executeScript("return localStorage.getItem(\"userID\")")
    if (!!await driver.executeScript("return (arguments[0] == null)", vars["userID"])) {
      await driver.get("http://localhost:3000/login")
      await driver.findElement(By.id("email")).sendKeys("test@test.test")
      await driver.findElement(By.id("password")).sendKeys("test123")
      await driver.findElement(By.css(".btn")).click()
      await driver.wait(until.alertIsPresent(), 2000);
      let alert = await driver.switchTo().alert();
      console.log(alert.getText());
      await driver.sleep(3000);
      await alert.getText().then(function(text) {
        assert(text == "Login successfully!");
      }); 
      await alert.accept(); 
      vars["url"] = await driver.executeScript("return window.location.href;")
      assert(vars["url"].toString() == "http://localhost:3000/")
    }
    await driver.findElement(By.linkText("Delete User")).click()
    await driver.wait(until.alertIsPresent(), 2000);
    let alert1 = await driver.switchTo().alert();
    console.log(alert1.getText());
    await driver.sleep(3000);
    await alert1.getText().then(function(text) {
      assert(text == "User deleted successfully!");
    }); 
    await alert1.accept(); 
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("email")).sendKeys("test@test.test")
    await driver.findElement(By.id("password")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    const messageElement = await driver.findElement(By.id("message"));
    const messageText = await messageElement.getText();
    console.log(messageElement.getText());
    await driver.sleep(2000);
    assert.equal(messageText,"Email does not exists");
    await driver.get("http://localhost:3000/register")
    await driver.findElement(By.id("email")).sendKeys("test@test.test")
    await driver.findElement(By.id("password")).sendKeys("test123")
    await driver.findElement(By.id("cnfrm-password")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    await driver.wait(until.alertIsPresent(), 2000);
    let alert = await driver.switchTo().alert();
    console.log(alert.getText());
    await driver.sleep(3000);
    await alert.getText().then(function(text) {
      assert(text == "Registration successfully!");
    }); 
    await alert.accept(); 
  })
})
